/**
 * Universitat Autònoma de Barcelona
 * MiP 2019 - 2020
 * PROJECTE WHITEBOARD CLOCK
 * NIUS
 * Roger Gili 1497893
 * Albert Romero 1425095
 */

int CLEAR_WHITEBOARD_SERVO_I[]={150,50,130,150,150,65,50,150};
int CLEAR_WHITEBOARD_SERVO_D[]={120,10,80,120,90,25,25,120};


//HORAS PRIMER DIGITO
int HOURS_FIRST_DIGIT_0_SERVO_I[] = {130,90,90,125,130};
int HOURS_FIRST_DIGIT_0_SERVO_D[] = {80,90,80,70,80};
int HOURS_FIRST_DIGIT_1_SERVO_I[] = {};
int HOURS_FIRST_DIGIT_1_SERVO_D[] = {};
int HOURS_FIRST_DIGIT_2_SERVO_I[] = {};
int HOURS_FIRST_DIGIT_2_SERVO_D[] = {};

//HORAS SEGUNDO DIGITO
int HOURS_SECOND_DIGIT_0_SERVO_I[] = {60,70,70,60,50,55,60};
int HOURS_SECOND_DIGIT_0_SERVO_D[] = {120,110,90,80,100,110,120};
int HOURS_SECOND_DIGIT_1_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_1_SERVO_D[] = {};
int HOURS_SECOND_DIGIT_2_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_2_SERVO_D[] = {};
int HOURS_SECOND_DIGIT_3_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_3_SERVO_D[] = {};
int HOURS_SECOND_DIGIT_4_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_4_SERVO_D[] = {};
int HOURS_SECOND_DIGIT_5_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_5_SERVO_D[] = {};
int HOURS_SECOND_DIGIT_6_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_6_SERVO_D[] = {};
int HOURS_SECOND_DIGIT_7_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_7_SERVO_D[] = {};
int HOURS_SECOND_DIGIT_8_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_8_SERVO_D[] = {};
int HOURS_SECOND_DIGIT_9_SERVO_I[] = {};
int HOURS_SECOND_DIGIT_9_SERVO_D[] = {};



//MINUTOS PRIMER DIGITO
int MINUTES_FIRST_DIGIT_0_SERVO_I[] = {};
int MINUTES_FIRST_DIGIT_0_SERVO_D[] = {};
int MINUTES_FIRST_DIGIT_1_SERVO_I[] = {};
int MINUTES_FIRST_DIGIT_1_SERVO_D[] = {};
int MINUTES_FIRST_DIGIT_2_SERVO_I[] = {};
int MINUTES_FIRST_DIGIT_2_SERVO_D[] = {};
int MINUTES_FIRST_DIGIT_3_SERVO_I[] = {};
int MINUTES_FIRST_DIGIT_3_SERVO_D[] = {};
int MINUTES_FIRST_DIGIT_4_SERVO_I[] = {};
int MINUTES_FIRST_DIGIT_4_SERVO_D[] = {};
int MINUTES_FIRST_DIGIT_5_SERVO_I[] = {};
int MINUTES_FIRST_DIGIT_5_SERVO_D[] = {};


//MINUTOS SEGUNDO DIGITO
int MINUTES_SECOND_DIGIT_0_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_0_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_1_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_1_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_2_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_2_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_3_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_3_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_4_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_4_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_5_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_5_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_6_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_6_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_7_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_7_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_8_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_8_SERVO_D[] = {};
int MINUTES_SECOND_DIGIT_9_SERVO_I[] = {};
int MINUTES_SECOND_DIGIT_9_SERVO_D[] = {};


//THE : SEPARATOR
int SEPARATOR_SERVO_I_S[] = {100,97};
int SEPARATOR_SERVO_D_S[] = {50,48};
int SEPARATOR_SERVO_I_I[] = {75,77};
int SEPARATOR_SERVO_D_I[] = {55,48};
